CREATE USER username WITH PASSWORD 'password';

CREATE DATABASE dbh OWNER username;

\connect dbh;

CREATE TABLE IF NOT EXISTS pings (
    id SERIAL PRIMARY KEY,
    message TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO username;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO username;
